 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/reads", type: :request do
  
  # Read. As you add validations to Read, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Read.create! valid_attributes
      get reads_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      read = Read.create! valid_attributes
      get read_url(read)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_read_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      read = Read.create! valid_attributes
      get edit_read_url(read)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Read" do
        expect {
          post reads_url, params: { read: valid_attributes }
        }.to change(Read, :count).by(1)
      end

      it "redirects to the created read" do
        post reads_url, params: { read: valid_attributes }
        expect(response).to redirect_to(read_url(Read.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Read" do
        expect {
          post reads_url, params: { read: invalid_attributes }
        }.to change(Read, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post reads_url, params: { read: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested read" do
        read = Read.create! valid_attributes
        patch read_url(read), params: { read: new_attributes }
        read.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the read" do
        read = Read.create! valid_attributes
        patch read_url(read), params: { read: new_attributes }
        read.reload
        expect(response).to redirect_to(read_url(read))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        read = Read.create! valid_attributes
        patch read_url(read), params: { read: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested read" do
      read = Read.create! valid_attributes
      expect {
        delete read_url(read)
      }.to change(Read, :count).by(-1)
    end

    it "redirects to the reads list" do
      read = Read.create! valid_attributes
      delete read_url(read)
      expect(response).to redirect_to(reads_url)
    end
  end
end
