version: "3.3"

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - 'redis:redis'
      - 'db:db'
    depends_on:
      - db
      - redis
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
  redis:
    restart: always
    image: redis:6.0.10
    volumes:
      - 'redis:/data'
    ports:
      - "6379:6379"

volumes:
  db_data:
  redis:
